(autoload 'crypt-build-encryption-alist         "crypt" "" nil)
(autoload 'crypt-build-encoding-alist           "crypt" "" nil)
(autoload 'crypt-rebuild-tables                 "crypt" "" t)
(autoload 'crypt-get-alist-member               "crypt" "" nil)
(autoload 'crypt-get-magic-regexp               "crypt" "" nil 'macro)
(autoload 'crypt-get-magic-regexp-inverse       "crypt" "" nil 'macro)
(autoload 'crypt-get-file-extension             "crypt" "" nil 'macro)
(autoload 'crypt-get-encoding-program           "crypt" "" nil 'macro)
(autoload 'crypt-get-decoding-program           "crypt" "" nil 'macro)
(autoload 'crypt-get-encoding-args              "crypt" "" nil 'macro)
(autoload 'crypt-get-decoding-args              "crypt" "" nil 'macro)
(autoload 'crypt-get-minor-mode-name            "crypt" "" nil 'macro)
(autoload 'crypt-get-cleanup-regexp             "crypt" "" nil 'macro)
(autoload 'crypt-get-extension-tricks           "crypt" "" nil 'macro)
(autoload 'crypt-get-encryption-key-stdin       "crypt" "" nil 'macro)
(autoload 'crypt-buffer-save-name               "crypt" "" nil)
(autoload 'crypt-build-minor-mode-alist         "crypt" "" nil)
(autoload 'crypt-rebuild-minor-modes-alist      "crypt" "" nil)
(autoload 'crypt-save-point                     "crypt" "" nil 'macro)
(autoload 'crypt-find-file-hook                 "crypt" "" nil)
(autoload 'crypt-encoded-p                      "crypt" "" nil)
(autoload 'crypt-encryption-type-get            "crypt" "" nil)
(autoload 'crypt-encryption-type-set            "crypt" "" nil)
(autoload 'crypt-encrypted-p                    "crypt" "" nil)
(autoload 'crypt-check-extension-for-encoding   "crypt" "" nil)
(autoload 'crypt-y-or-n-p                       "crypt" "" nil)
(autoload 'crypt-write-file-hook                "crypt" "" nil)
(autoload 'crypt-pgp-pub-clear-recipients       "crypt" "" t)
(autoload 'crypt-pgp-pub-npgp-userid            "crypt" "" nil)
(autoload 'crypt-pgp-pub-mailcrypt-userid       "crypt" "" nil)
(autoload 'crypt-pgp-pub-load-mailcrypt         "crypt" "" nil)
(autoload 'crypt-pgp-pub-decrypt-region         "crypt" "" nil)
(autoload 'crypt-pgp-pub-encrypt-region         "crypt" "" nil)
(autoload 'crypt-encrypt-region                 "crypt" "" t)
(autoload 'crypt-encrypt-buffer                 "crypt" "" nil)
(autoload 'crypt-decrypt-buffer                 "crypt" "" t)
(autoload 'crypt-encode-region                  "crypt" "" t)
(autoload 'crypt-encode-buffer                  "crypt" "" nil)
(autoload 'crypt-dos-to-unix-region             "crypt" "" nil)
(autoload 'crypt-unix-to-dos-region             "crypt" "" nil)
(autoload 'crypt-mac-to-unix-region             "crypt" "" nil)
(autoload 'crypt-unix-to-mac-region             "crypt" "" nil)
(autoload 'crypt-encrypted-mode                 "crypt" "" t)
(autoload 'crypt-forget-encryption-key          "crypt" "" nil)
(autoload 'crypt-reset-passwd-timer             "crypt" "" nil)
(autoload 'crypt-reset-passwds-timeout          "crypt" "" nil)
(autoload 'crypt-symbol-alist-to-table          "crypt" "" nil)
(autoload 'crypt-read-encoding-type             "crypt" "" nil)
(autoload 'crypt-encoded-mode                   "crypt" "" t)
(autoload 'crypt-set-encryption-key             "crypt" "" t)
(autoload 'crypt-bind-insert-file               "crypt" "" t)
(autoload 'crypt-insert-file                    "crypt" "" t)
(autoload 'crypt-insert-file-contents           "crypt" "" nil)
(autoload 'crypt-submit-report                  "crypt" "" t)
(provide 'crypt-autoloads)
